### ISSUE TITLE
Version support

### ISSUE THREAD

**Issue by bopke** [FunnyGuilds/FunnySectors#4]
Minecraft version 1.8 is pretty old version of the game, but yet it is extremely popular these days. Supporting every version starting from 1.8 to modern version will present some difficulties, considering how much have changed in this almost 7 years timespan. This may be interesting problem to  tackle and I think we should really push for such wide game version span, because as we can se in [FunnyGuilds bStats](https://bstats.org/plugin/bukkit/FunnyGuilds/677), 1.8.8 version makes up over 45% of all server running it. Share you thoughts in this issue, if you think another solution would be better.

**Comment by WcaleNieWolny** [comment]
Honestly? I could agree with the 1.8 support but I think the only versions that would be officially supported would be:
- 1.18
- 1.17
- 1.8

Supporting any other version is a waste of our time

**Comment by sadcenter** [comment]
what about 1.12

**Comment by WcaleNieWolny** [comment]
Well... I do not think 1.12 is important. 1.12 server did not migrate to 1.13 due to changes in ID system and lags with large player count on 1.13 however as Minecraft is progressing these problems get more and more less significant. It is possible that by the time we will be done with this project latest Minecraft version will be more efficient than 1.12. Even [2B2T](https://en.wikipedia.org/wiki/2b2t) had attempted [1.18 migration](https://www.reddit.com/r/2b2t/comments/tc3zjn/118_test_server_online_on_original_world/)

**Comment by thatbakamono** [comment]
We should also support 1.16.5, as you can see in the statistics, it's far more popular than 1.18.2 or 1.17.2 (which we intend to support, no?)

**Comment by WcaleNieWolny** [comment]
Honestly? I do not think supporting 1.16 at the start of the project is a good idea. By the time we finish project 1.16 might be obsolete. If not we will just add support for it. The same could be said about 1.12

**Comment by oskarscot** [comment]
I think all versions from 1.8 to 1.18 should be supported especially with 1.8, 1.12, 1.16, 1.17 and 1.18 being really popular.

**Comment by thatbakamono** [comment]
> Honestly? I do not think supporting 1.16 at the start of the project is a good idea. By the time we finish project 1.16 might be obsolete. If not we will just add support for it. The same could be said about 1.12

At the beginning of the project we should support only 1.8.8, there is no way we can add support for multiple versions at once, we will add support for the rest as the project matures.

**Comment by WcaleNieWolny** [comment]
> At the beginning of the project we should support only 1.8.8, there is no way we can add support for multiple versions at once, we will add support for the rest as the project matures.

I disagree. I think we shoudl start with 1.18 and support 1.8 later. It is easy to add support for 1.17, 1.16 but adding support from 1.8 to 1.18 will be difficult

**Comment by WcaleNieWolny** [comment]
> I think all versions from 1.8 to 1.18 should be supported especially with 1.8, 1.12, 1.16, 1.17 and 1.18 being really popular.

Well... Why woudl we spend time on versions like 1.9 or 1.10? Almost no big server is running these

**Comment by thatbakamono** [comment]
> > At the beginning of the project we should support only 1.8.8, there is no way we can add support for multiple versions at once, we will add support for the rest as the project matures.
> 
> I disagree. I think we shoudl start with 1.18 and support 1.8 later. It is easy to add support for 1.17, 1.16 but adding support from 1.8 to 1.18 will be difficult

It's going to be a lot harder to add support for 1.8 if we start with 1.18 as the former lacks features, it's usually way easier to add support for newer versions once you support older, so we should start with 1.8.

**Comment by thatbakamono** [comment]
> > I think all versions from 1.8 to 1.18 should be supported especially with 1.8, 1.12, 1.16, 1.17 and 1.18 being really popular.
> 
> Well... Why woudl we spend time on versions like 1.9 or 1.10? Almost no big server is running these

Most versions don't add anything significant that requires us to write additional code so in theory we could easily support versions like 1.9 or 1.10 but I agree, I don't think there is a reason to support them.

**Comment by bopke** [comment]
> At the beginning of the project we should support only 1.8.8, there is no way we can add support for multiple versions at once, we will add support for the rest as the project matures.

I thought about this topic and I 100% agree with @thatbakamono. We need to keep our initial goal as close as possible, to decrease chance of burnout and leaving the project.

I think this thread is concluded but will keep it open till the end of the weekend for some final thoughs, if anyone has any.
