### ISSUE TITLE
Plugin platforms

### ISSUE THREAD

**Issue by bopke** [FunnyGuilds/FunnySectors#5]
As for the minecraft server, I think there is no doubt that only spigot is now a viable platform. But for the proxy server there are two widely used platforms - velocity and bungeecord. I've did a little bit of research and it appears that velocity is way more robust and uses less resources, nonetheless I've seen traces that bungeecord is still in use. I think that supporting one of them as recommended platform and second one as optional way is a good idea. I do not have much experience with creating proxy plugins, so I'm opening this discussion issue to hear your for or against voices so we could make the best decission possible.

**Comment by WcaleNieWolny** [comment]
Well... I agree we should support velocity and bungee **HOEVER** later on we might end up supporting dynamic mode only on on of these platforms. I think we should check for the possibility of seamless player server transport before we make a decision or at least a way to suspend player on the proxy for about 10 seconds without any upstream sever and without kicking player

**Comment by thatbakamono** [comment]
I think we should support both **but** our recommended proxy platform should definitely be Velocity, as you said, it's far better in many aspects.

**Comment by thatbakamono** [comment]
As was discussed on Bookkity, Bungeecord and Velocity are very similar in terms of features and most existing plugins for them won't work with sectors without major changes anyway so I think we should only support Velocity, it's gonna reduce the scope of the project by a lot.

**Comment by bopke** [comment]
> most existing plugins for them won't work with sectors without major changes anyway

That's a valid point. Now bungeecord plugin looks like obsolete legacy code from the very moment it would be written.

Lets just stick to the velocity.

I think this thread is concluded but will keep it open till the end of the weekend for some final thoughs, if anyone has any.
