### ISSUE TITLE
Addons and API

### ISSUE THREAD

**Issue by oskarscot** [FunnyGuilds/FunnySectors#8]
We'd have to replace the behaviour of a lot of popular plugins i.e typical combat log plugin. 

This can be done by either adding it directly into the plugin (like FG) or by creating addons. This is because for example a typical combat log plugin kill the player whilst leaving the server during combat time, this would also happen during sector switch ultimately leading to item copying.

The project should be designed in a way where it's as modular as possible.

**Comment by WcaleNieWolny** [comment]
As the [project proposal](https://github.com/WcaleNieWolny/FunnySectors/blob/main/project%20overview.md):

> api - developer API used to serialize data between servers

The API would provide a way to send and receive data on sector change as well as sector status etc

**Comment by bopke** [comment]
No plugin should be added directly into the plugin, not even FG. This plugin should, and at some point just will provide API to cooperate with other plugins.

**Comment by WcaleNieWolny** [comment]
agree
